import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-slate-500 h-screen">
          <div className="bg-cyan-600 flex justify-center h-20 text-5xl text-slate-200">
            <div className="my-auto">hello this is my app</div>
          </div>
          <div className="flex justify-center">
          <div className="p-8 bg-red-500 flex justify-center m-6 rounded-full">
              this is a button
            </div>
            </div>
        </div>
      </main>
    </>
  )
}
